#!/usr/bin/env python3
import serial
import time
import argparse
import csv
from datetime import datetime

def twos_complement_to_int(value, bits=24):
    """
    Convert a two's complement value to a signed integer.
    
    Args:
        value (int): The two's complement value as an unsigned integer
        bits (int): Number of bits in the two's complement representation
        
    Returns:
        int: The signed integer value
    """
    if (value & (1 << (bits - 1))) != 0:  # If sign bit is set
        value = value - (1 << bits)       # Compute negative value
    return value

def receive_uart_data_to_csv(port, baudrate=9600, timeout=1, output_file=None):
    """
    Receives data from the specified serial port, separates the first byte (byte0),
    and processes the remaining 3 bytes as a 24-bit two's complement number.
    Writes the data to a CSV file.
    
    Args:
        port (str): Serial port name (e.g., 'COM3' on Windows, '/dev/ttyUSB0' on Linux)
        baudrate (int): Baud rate (default: 9600)
        timeout (int): Serial timeout in seconds (default: 1)
        output_file (str): CSV file name (default: autogenerated based on timestamp)
        
    Returns:
        tuple: Two arrays containing command bytes and 24-bit values
    """
    # Initialize arrays
    command_bytes = []  # First byte (byte0) - command or identifier
    values_24bit = []   # 24-bit two's complement values
    
    # Generate default output filename if not provided
    if output_file is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = f"uart_data_{timestamp}.csv"
    
    try:
        # Open the serial port
        ser = serial.Serial(port, baudrate, timeout=timeout)
        print(f"Connected to {port} at {baudrate} baud")
        print(f"Data will be saved to {output_file}")
        
        # Create and open CSV file
        with open(output_file, 'w', newline='') as csvfile:
            fieldnames = ['packet_num', 'command_byte', 'byte1', 'byte2', 'byte3', 
                         'raw_24bit_value', 'signed_value']
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()
            
            # Counter to track byte position
            byte_counter = 0
            word_counter = 0
            current_word = {}
            
            while True:
                # Read a byte from the serial port
                data = ser.read(1)
                
                if data:
                    # Convert byte to integer
                    byte_value = int.from_bytes(data, byteorder='big')
                    
                    # Determine which position in the 32-bit word
                    position = byte_counter % 4
                    
                    if position == 0:
                        # First byte - command or identifier
                        command_bytes.append(byte_value)
                        current_word = {'packet_num': word_counter, 'command_byte': byte_value}
                        print(f"Command byte: {byte_value}")
                    elif position == 1:
                        # MSB of 24-bit value
                        current_word['byte1'] = byte_value
                        print(f"Byte 1 (MSB of 24-bit value): {byte_value}")
                    elif position == 2:
                        current_word['byte2'] = byte_value
                        print(f"Byte 2: {byte_value}")
                    elif position == 3:
                        # LSB of 24-bit value
                        current_word['byte3'] = byte_value
                        
                        # Calculate the 24-bit value (byte1 is MSB)
                        raw_24bit = (current_word['byte1'] << 16) | (current_word['byte2'] << 8) | byte_value
                        current_word['raw_24bit_value'] = f"0x{raw_24bit:06X}"
                        
                        # Convert to signed value using two's complement
                        signed_value = twos_complement_to_int(raw_24bit, 24)
                        current_word['signed_value'] = signed_value
                        values_24bit.append(signed_value)
                        
                        # Write the complete word to the CSV
                        writer.writerow(current_word)
                        csvfile.flush()  # Ensure data is written to disk
                        
                        print(f"Byte 3 (LSB): {byte_value}")
                        print(f"24-bit raw value: {current_word['raw_24bit_value']}")
                        print(f"Signed value: {signed_value}\n")
                        
                        word_counter += 1
                    
                    # Increment byte counter
                    byte_counter += 1
                    
    except KeyboardInterrupt:
        print("\nReceiver stopped by user")
    except serial.SerialException as e:
        print(f"Error: {e}")
    finally:
        if 'ser' in locals() and ser.is_open:
            ser.close()
            print("Serial port closed")
        
        # Print summary
        print("\nReceived data summary:")
        print(f"Total packets received: {len(values_24bit)}")
        print(f"Data saved to {output_file}")
        
        return command_bytes, values_24bit

if __name__ == "__main__":
  
    receive_uart_data_to_csv("COM9", 921600, 1)